columns_to_drop: ['genres', 'original_title', 'overview', 'vote_count','vote_average','popularity']

raw_data_path: 'Artifacts/raw_data'
preprocessed_data_path: 'Artifacts/preprocessed_data'
embeddings_folder: 'Artifacts/embeddings'

# S3 bucket configuration
bucket: 'beansbucket12'
key: 'lancedb34/movies_metadata.csv'

uri: 'Artifacts/LanceDatabase'

